### PR TITLE
Daniel

### PR DESCRIPTION
**Pull request by interrogator**
Sorry guys, I had to rename the massive folder. Promise no further revisions to it.

@FCTweedie , `day-1.py/day-1.ipynb` notebook should now be close to a state where we can send it out to our helpers. Can you take a final look at it?

This eve I'm going to fill in the missing parts of session 4. It'd be great if you could add in whatever final messages need to be in the end of session 6. Aside from typos etc, I think session 5 is done.

### CODE REVIEW

**Comment by interrogator** [comment]
thanks, old sport.

**Comment by datakid** [comment]
One thing. @interrogator can I ask that you commit more frequently pls? Either every major change (eg moving a folder or recreating a ipynb for instance) or every dozen minor changes (to large files). Some of those changes were so big I missed the important changes :) My own damn fault for not being 100% thorough. But yes, commit early, commit often!

**Comment by datakid** [comment]
:) No problems.

**Comment by interrogator** [comment]
@datakid : still getting over my fear of commitment. but yeah, sure!

**Pull request merged**
