### PR TITLE
adding corpora, corpling_tools, updated sessions

### PR DESCRIPTION
**Pull request by interrogator**
Hey guys, this is my first commit to the resbaz master, hope I'm doing it right!

### CODE REVIEW

**Comment by DamienIrving** [comment]
@interrogator (cc. @FCTweedie) Yep, submitting a PR is the way to go. Also happy for you to merge your own PRs, however maybe wait an hour or two in future in case anyone has comments. For instance, my concern is that there are now 800+ files in `resbaz/lessons/nltk`, which means whenever someone clones the lesson repo, it represents a fairly big chunk of stuff. You might want to consider whether all the data files you've included in the repo really need to be under version control, and if they do we might have to look at creating a brand new repo for nltk (i.e. `resbaz/nltk`) to separate it from the rest of the lessons repo.

**Comment by interrogator** [comment]
Sorry Damien, still learning the ropes!

The files are just corpus text files, and won't really be edited, so version control's not an issue.

Do you think we should zip the files up and host them on GitHub, or should we store them somewhere else (any suggestions where?)

Daniel

On Feb 10, 2015, at 10:26 AM, Damien Irving wrote:


@interrogator<https://github.com/interrogator> (cc. @FCTweedie<https://github.com/FCTweedie>) Yep, submitting a PR is the way to go. Also happy for you to merge your own PRs, however maybe wait an hour or two in future in case anyone has comments. For instance, my concern is that there are now 800+ files in resbaz/lessons/nltk, which means whenever someone clones the lesson repo, it represents a fairly big chunk of stuff. You might want to consider whether all the data files you've included in the repo really need to be under version control, and if they do we might have to look at creating a brand new repo for nltk (i.e. resbaz/nltk) to separate it from the rest of the lessons repo.

**Comment by DamienIrving** [comment]
@interrogator No need to apologise. Most of these processes we just make up as we go along! 

Are the data easy to download from a website / data server somewhere? If so, I'd suggest getting the participants to do that rather than having us host a separate copy.

For data that aren't easily available elsewhere, I can't really think of a good place to host. In that case, it is probably a good idea to leave it on GitHub because despite the fact we don't really need to version the data (because it won't be changing), it makes it easy for the participants to get (i.e. they can just type `git clone` at the command line). If it's lots of files, however, I would suggest making a stand alone `lessons/nltk` repo so others working on the lessons repo don't have to clone an enormous amount of files.

**Comment by FCTweedie** [comment]
Have you done some processing on the files, Daniel, or are they the ones from the UM Archives site?
If the latter, we can get them to load in via filemanager (I was also planning to have them on a usb in case)

**Comment by interrogator** [comment]
@FCTweedie : one folder (`UMA_Fraser_Radio_Talks`) is just a combination of the corrected batch we got via email and the ones available via unimelb. Another folder (`fraser-corpus-annotated`) has the parsed versions, but they're easy, as I've concatenated that into one file per year. There is also the ozpolitics forum as a single txt file.

@DamienIrving : Perhaps the compromise is just zipping the files up and having the participants run an unzip command after downloading? Or is that not good practice?

I'd like to keep everything on GitHub where possible, as it's good to be able to point everyone to the same spot for additional resources.

**Comment by datakid** [comment]
I think it's fine to just leave it there, since it wont be changing much
and have been put into a well formed file system. Zipping shouldn't be
necessary - they are all txt files on the whole, so git will compress on
the fly, and binary blobs change too easily.

Daniel, it is a well formed file system right? I've not checked. But right
files in the right folders, well named files?

------
"This is a profound psychological violence here. How can one even begin to
speak of dignity in labor when one secretly feels one's job should not
exist?"

On the Phenomenon of Bullshit Jobs, David Graeber
http://strikemag.org/bullshit-jobs/

**Comment by DamienIrving** [comment]
I agree with @datakid - sounds like having them on GitHub (but perhaps in a new `resbaz/nltk` repo) might be the way to go. I also agree that you don't need to worry about zipping.

**Comment by interrogator** [comment]
@datakid : yep, the structuring and naming is sensible, and we use every last bit of every file in there.

@DamienIrving : alright, we'll leave it all there for now, perhaps look for different host after ResBaz...

@everyone, GitHub is fun.

**Comment by datakid** [comment]
Damien,

I think that you are right wrt splitting the resbaz lessons into separate
repos, although I think that's something for post-ResBaz, due to proximity
to event and relative paths within the NLTK lesson (in particular) that
would need to be changed.


------
"This is a profound psychological violence here. How can one even begin to
speak of dignity in labor when one secretly feels one's job should not
exist?"

On the Phenomenon of Bullshit Jobs, David Graeber
http://strikemag.org/bullshit-jobs/

**Comment by resbaz** [comment]
Yep, was just going to suggest separate repos in future. Arguably for each
of the tools.

On Tue, Feb 10, 2015 at 11:32 AM, Lachlan Musicman <notifications@github.com
> wrote:

> Damien,
>
> I think that you are right wrt splitting the resbaz lessons into separate
> repos, although I think that's something for post-ResBaz, due to proximity
> to event and relative paths within the NLTK lesson (in particular) that
> would need to be changed.
>
>
> ------
> "This is a profound psychological violence here. How can one even begin to
> speak of dignity in labor when one secretly feels one's job should not
> exist?"
>
> On the Phenomenon of Bullshit Jobs, David Graeber
> http://strikemag.org/bullshit-jobs/
>

**Comment by DamienIrving** [comment]
@datakid Agreed

**Pull request merged**
